USE DataAnalysis;
CREATE TABLE CitiesData (CityName VARCHAR(200) NOT NULL, CityType VARCHAR(100) NOT NULL, 
Division VARCHAR(100) NOT NULL, PopulationLatest BIGINT NOT NULL, PopulationPrevious BIGINT NOT NULL, 
Area BIGINT NOT NULL, PRIMARY KEY(CityName));