services:
# Ontario Scraper App Configuration
  ontario-spider:
    restart: always
    container_name: ontario-spider
    image: ghcr.io/kunalmehta14/realestate-datapipeline:1
    volumes:
      - ./ontario-spider/app:/opt/app
      - type: volume
        source: scrapy_images
        target: /opt/app/spiders/Images
    environment:
      - CIFS_USERNAME=${CIFS_USERNAME}
      - CIFS_PASSWORD=${CIFS_PASSWORD}

# British Columbia Scraper App Configuration
  britishcolumbia-spider:
    restart: always
    container_name: britishcolumbia-spider
    image: ghcr.io/kunalmehta14/realestate-datapipeline:1
    volumes:
      - ./britishcolumbia-spider/app:/opt/app
      - type: volume
        source: scrapy_images
        target: /opt/app/spiders/Images
    environment:
      - CIFS_USERNAME=${CIFS_USERNAME}
      - CIFS_PASSWORD=${CIFS_PASSWORD}
# Alberta Scraper App Configuration
  alberta-spider:
    restart: always
    container_name: alberta-spider
    image: ghcr.io/kunalmehta14/realestate-datapipeline:1
    volumes:
      - ./alberta-spider/app:/opt/app
      - type: volume
        source: scrapy_images
        target: /opt/app/spiders/Images
    environment:
      - CIFS_USERNAME=${CIFS_USERNAME}
      - CIFS_PASSWORD=${CIFS_PASSWORD}

# Shared Folder
volumes:
  scrapy_images:
    driver_opts:
      type: cifs
      o: username=${CIFS_USERNAME},password=${CIFS_PASSWORD},file_mode=0777,dir_mode=0777
      device: ${CIFS_SHARE}