services:
# Ontario Scraper App Configuration
  ontario-spider:
    restart: always
    container_name: ontario-spider
    image: ghcr.io/kunalmehta14/realestate-datapipeline:1
    volumes:
      - ./ontario-spider/app:/opt/app
      - /opt/scrapy-images/images-db1:/opt/app/spiders/Images
    privileged: true
# British Columbia Scraper App Configuration
  britishcolumbia-spider:
    restart: always
    container_name: britishcolumbia-spider
    image: ghcr.io/kunalmehta14/realestate-datapipeline:1
    volumes:
      - ./britishcolumbia-spider/app:/opt/app
      - /opt/scrapy-images/images-db1:/opt/app/spiders/Images
    privileged: true
# Alberta Scraper App Configuration
  alberta-spider:
    restart: always
    container_name: alberta-spider
    image: ghcr.io/kunalmehta14/realestate-datapipeline:1
    volumes:
      - ./alberta-spider/app:/opt/app
      - /opt/scrapy-images/images-db1:/opt/app/spiders/Images
    privileged: true

# Monitoring Services
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"